[package]
name = "rust_book"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hello_world"
path = "src/hello_world/hello.rs"

[[bin]]
name = "guessing_game"
path = "src/guessing_game/main.rs"

[[bin]]
name = "variables"
path = "src/variables/main.rs"

[[bin]]
name = "data_type"
path = "src/data_type/main.rs"

[dependencies]
rand = "0.8.4"